"""
Drug Hunter — All 20 disease cases
Developed by Sarang Dhote, Shivaji Science College, Nagpur
Pure data — no imports.
"""

CASES = [
    # ── 1. PAIN & INFLAMMATION ──────────────────────────────────────────────
    {
        "id": 1, "title": "The Painful Truth",
        "disease": "Pain & Inflammation (Rheumatoid Arthritis)",
        "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Mrs. Sharma", "age": 58, "gender": "Female",
            "condition": "Chronic rheumatoid arthritis — joint pain, swelling, redness",
            "history": "Took ibuprofen for 3 years → hospitalized with stomach bleeding"},
        "stage1_question": "Which enzyme produces prostaglandins that cause joint inflammation?",
        "stage1_options": [
            {"text": "Lipoxygenase (LOX)", "correct": False, "feedback": "LOX makes leukotrienes, not prostaglandins."},
            {"text": "Cyclooxygenase-2 (COX-2)", "correct": True, "feedback": "Correct! COX-2 makes prostaglandins during inflammation. COX-1 protects the stomach."},
            {"text": "Phospholipase A2", "correct": False, "feedback": "PLA2 releases arachidonic acid but doesn't directly make prostaglandins."},
            {"text": "Acetylcholinesterase", "correct": False, "feedback": "Wrong system — that enzyme breaks down acetylcholine in nerve synapses."},
        ],
        "target_protein": "COX-2", "target_pdb": "3LN1",
        "pocket_regions": [
            {"name": "Surface loop (outside pocket)", "correct": False, "feedback": "Far from the catalytic site."},
            {"name": "Hydrophobic pocket near Val523", "correct": True, "feedback": "Correct! Val523 in COX-2 vs Ile523 in COX-1 is the key selectivity difference."},
            {"name": "Membrane-binding domain", "correct": False, "feedback": "That anchors COX-2 to the membrane — not the drug binding site."},
            {"name": "Dimer interface", "correct": False, "feedback": "Where two subunits meet — not where drugs bind."},
        ],
        "candidates": [
            {"name": "Celecoxib",       "desc": "Selective COX-2 inhibitor",          "smiles": "CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F", "kind": "best"},
            {"name": "Aspirin",         "desc": "Old non-selective NSAID",             "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                                    "kind": "weak"},
            {"name": "Ibuprofen",       "desc": "Non-selective NSAID",                 "smiles": "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O",                              "kind": "weak"},
            {"name": "Diphenhydramine", "desc": "Decoy — antihistamine",               "smiles": "CN(C)CCOC(C1=CC=CC=C1)C2=CC=CC=C2",                           "kind": "decoy"},
            {"name": "Rofecoxib",       "desc": "COX-2 selective (withdrawn 2004)",    "smiles": "CS(=O)(=O)C1=CC=C(C=C1)C2=C(C(=O)OC2)C3=CC=CC=C3",           "kind": "alt"},
            {"name": "Glucose",         "desc": "Decoy — sugar",                       "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                                   "kind": "decoy"},
        ],
        "off_target": "COX-1", "off_target_pdb": "3KK6",
        "selectivity_data": {
            "Celecoxib": {"pass": True,  "msg": "Excellent — fits large COX-2 pocket, blocked by Ile523 in COX-1."},
            "Rofecoxib": {"pass": True,  "msg": "Selective — but cardiac risk led to FDA withdrawal in 2004."},
        },
        "admet": {
            "Celecoxib": {"MW": 381, "LogP": 3.5, "HBD": 1, "HBA": 7,  "RotBonds": 4,  "pass": True,  "warning": None},
            "Rofecoxib": {"MW": 314, "LogP": 2.7, "HBD": 0, "HBA": 4,  "RotBonds": 2,  "pass": True,  "warning": "⚠️ FDA withdrew Vioxx in 2004 — 40% increased heart attack risk."},
        },
        "ending": "Mrs. Sharma's joints feel great and her stomach is fine. Selective inhibition solved her problem.",
    },
    # ── 2. HYPERTENSION ─────────────────────────────────────────────────────
    {
        "id": 2, "title": "Pressure Mounting",
        "disease": "Hypertension", "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Mr. Patel", "age": 62, "gender": "Male",
            "condition": "Persistent high blood pressure (160/100 mmHg)",
            "history": "Lifestyle changes and diet failed. Needs pharmacological treatment."},
        "stage1_question": "Which enzyme converts angiotensin I to angiotensin II (a vasoconstrictor)?",
        "stage1_options": [
            {"text": "Renin", "correct": False, "feedback": "Renin acts earlier — converts angiotensinogen to angiotensin I."},
            {"text": "Angiotensin Converting Enzyme (ACE)", "correct": True, "feedback": "Correct! ACE converts angiotensin I → angiotensin II, constricting blood vessels."},
            {"text": "Aldosterone Synthase", "correct": False, "feedback": "Aldosterone synthase acts downstream of angiotensin II."},
            {"text": "Bradykininase", "correct": False, "feedback": "Bradykininase is another name for ACE — use the standard term."},
        ],
        "target_protein": "ACE", "target_pdb": "1O86",
        "pocket_regions": [
            {"name": "N-terminal helix", "correct": False, "feedback": "Far from the active site."},
            {"name": "Zinc-binding catalytic site", "correct": True, "feedback": "Correct! ACE is a zinc metallopeptidase — drugs chelate the Zn²⁺."},
            {"name": "Membrane anchor region", "correct": False, "feedback": "Anchors ACE to the cell surface."},
            {"name": "Glycosylation surface", "correct": False, "feedback": "Just sugar decoration on the protein."},
        ],
        "candidates": [
            {"name": "Captopril",   "desc": "First ACE inhibitor",        "smiles": "CC(CS)C(=O)N1CCCC1C(=O)O",                                  "kind": "best"},
            {"name": "Lisinopril",  "desc": "Modern ACE inhibitor",       "smiles": "NCCCCC(NC(CCc1ccccc1)C(=O)O)C(=O)N1CCCC1C(=O)O",           "kind": "alt"},
            {"name": "Paracetamol", "desc": "Decoy — painkiller",         "smiles": "CC(=O)Nc1ccc(O)cc1",                                        "kind": "decoy"},
            {"name": "Aspirin",     "desc": "Decoy — anti-inflammatory",  "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                                  "kind": "decoy"},
            {"name": "Caffeine",    "desc": "Decoy — stimulant",          "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",                             "kind": "decoy"},
            {"name": "Enalaprilat", "desc": "Active form of enalapril",   "smiles": "CCOC(=O)C(CCc1ccccc1)NC(C)C(=O)N1CCCC1C(=O)O",            "kind": "weak"},
        ],
        "off_target": "ACE2", "off_target_pdb": "1R42",
        "selectivity_data": {
            "Captopril":  {"pass": True, "msg": "Good selectivity. May cause dry cough via bradykinin buildup."},
            "Lisinopril": {"pass": True, "msg": "Excellent selectivity over ACE2."},
        },
        "admet": {
            "Captopril":  {"MW": 217, "LogP": 0.3,  "HBD": 2, "HBA": 4, "RotBonds": 4,  "pass": True,  "warning": None},
            "Lisinopril": {"MW": 405, "LogP": -1.2, "HBD": 5, "HBA": 8, "RotBonds": 12, "pass": False, "warning": "⚠️ Violates Lipinski rules but works via active transport."},
        },
        "ending": "Mr. Patel's BP drops to 130/85. Back to morning walks with his grandchildren.",
    },
    # ── 3. ALZHEIMER'S ──────────────────────────────────────────────────────
    {
        "id": 3, "title": "The Forgetting Mind",
        "disease": "Alzheimer's Disease", "difficulty": "⭐⭐⭐ Intermediate",
        "patient": {"name": "Mr. Singh", "age": 72, "gender": "Male",
            "condition": "Progressive memory loss, confusion, difficulty recognizing family",
            "history": "Worsening for 2 years. Brain imaging shows cortical thinning."},
        "stage1_question": "Acetylcholine is low in Alzheimer's. Which enzyme breaks it down?",
        "stage1_options": [
            {"text": "Choline acetyltransferase (ChAT)", "correct": False, "feedback": "ChAT MAKES acetylcholine — inhibiting it worsens disease."},
            {"text": "Acetylcholinesterase (AChE)",       "correct": True,  "feedback": "Correct! AChE breaks down acetylcholine. Inhibiting it raises synaptic levels."},
            {"text": "Monoamine oxidase (MAO)",           "correct": False, "feedback": "MAO breaks down dopamine/serotonin, not acetylcholine."},
            {"text": "COMT",                              "correct": False, "feedback": "COMT breaks down catecholamines, not acetylcholine."},
        ],
        "target_protein": "AChE", "target_pdb": "4EY7",
        "pocket_regions": [
            {"name": "Peripheral anionic site (PAS)", "correct": False, "feedback": "PAS is at the gorge entrance — catalytic site is deeper."},
            {"name": "Catalytic triad at gorge bottom","correct": True,  "feedback": "Correct! AChE has a deep gorge with Ser-His-Glu triad at the bottom."},
            {"name": "Surface helix",                  "correct": False, "feedback": "Wrong location."},
            {"name": "Dimerization interface",         "correct": False, "feedback": "Where subunits meet — not the active site."},
        ],
        "candidates": [
            {"name": "Donepezil",    "desc": "Selective AChE inhibitor (Aricept)",  "smiles": "COc1cc2c(cc1OC)CC(CC1CCN(Cc3ccccc3)CC1)C2=O",  "kind": "best"},
            {"name": "Galantamine",  "desc": "Natural alkaloid AChE inhibitor",     "smiles": "COC1=CC=C2CN3CCC4=CC(=C(OC5=C4C2=C1OC53)O)OC", "kind": "alt"},
            {"name": "Rivastigmine", "desc": "Dual AChE/BuChE inhibitor",           "smiles": "CCN(C)C(=O)Oc1cccc(C(C)N(C)C)c1",               "kind": "weak"},
            {"name": "Memantine",    "desc": "Decoy — NMDA antagonist",             "smiles": "CC12CC3CC(C1)(CC(C2)C3)N",                       "kind": "decoy"},
            {"name": "Aspirin",      "desc": "Decoy — NSAID",                       "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                      "kind": "decoy"},
            {"name": "Vitamin C",    "desc": "Decoy — antioxidant",                 "smiles": "C(C(C1C(=C(C(=O)O1)O)O)O)O",                    "kind": "decoy"},
        ],
        "off_target": "BuChE", "off_target_pdb": "1P0I",
        "selectivity_data": {
            "Donepezil":   {"pass": True, "msg": "Highly selective for AChE — minimal peripheral effects."},
            "Galantamine": {"pass": True, "msg": "Reasonable selectivity. Also activates nicotinic receptors."},
        },
        "admet": {
            "Donepezil":   {"MW": 379, "LogP": 4.3, "HBD": 0, "HBA": 4, "RotBonds": 6, "pass": True, "warning": "Crosses blood-brain barrier well (LogP 4.3) — essential for CNS drugs."},
            "Galantamine": {"MW": 287, "LogP": 1.1, "HBD": 1, "HBA": 4, "RotBonds": 1, "pass": True, "warning": None},
        },
        "ending": "Mr. Singh's family reports he's more responsive. He recognized his granddaughter's birthday.",
    },
    # ── 4. ERECTILE DYSFUNCTION ─────────────────────────────────────────────
    {
        "id": 4, "title": "Blood Flow Blues",
        "disease": "Erectile Dysfunction", "difficulty": "⭐⭐⭐ Intermediate",
        "patient": {"name": "Mr. Verma", "age": 54, "gender": "Male",
            "condition": "Erectile dysfunction affecting quality of life",
            "history": "No cardiovascular contraindications. Otherwise healthy."},
        "stage1_question": "To maintain an erection, cGMP must stay high. Which enzyme degrades cGMP?",
        "stage1_options": [
            {"text": "Phosphodiesterase type 5 (PDE5)", "correct": True,  "feedback": "Correct! PDE5 degrades cGMP. Blocking it keeps blood vessels dilated."},
            {"text": "Adenylyl cyclase",                "correct": False, "feedback": "Adenylyl cyclase MAKES cAMP, not cGMP."},
            {"text": "Guanylyl cyclase",               "correct": False, "feedback": "Guanylyl cyclase MAKES cGMP — inhibiting it would worsen things."},
            {"text": "Nitric oxide synthase",          "correct": False, "feedback": "NOS makes nitric oxide, which is upstream of cGMP."},
        ],
        "target_protein": "PDE5", "target_pdb": "1UDT",
        "pocket_regions": [
            {"name": "GAF-A regulatory domain",    "correct": False, "feedback": "Where cGMP binds for regulation — not the catalytic site."},
            {"name": "Catalytic domain H-loop",    "correct": True,  "feedback": "Correct! H-loop closes around cGMP. Drugs mimic the guanine ring."},
            {"name": "N-terminal coiled-coil",     "correct": False, "feedback": "Where PDE5 dimerizes."},
            {"name": "Membrane interface",         "correct": False, "feedback": "PDE5 is cytoplasmic — no membrane interface."},
        ],
        "candidates": [
            {"name": "Sildenafil",  "desc": "First PDE5 inhibitor (Viagra)",         "smiles": "CCCc1nn(C)c2c1nc(c1cc(S(=O)(=O)N3CCN(C)CC3)ccc1OCC)[nH]c2=O", "kind": "best"},
            {"name": "Tadalafil",   "desc": "Long-acting PDE5 inhibitor (Cialis)",   "smiles": "CN1CC(=O)N2C(c3ccc4OCOc4c3)c3cc4ccccc4[nH]c3C2C1=O",          "kind": "alt"},
            {"name": "Vardenafil",  "desc": "PDE5 inhibitor (Levitra)",              "smiles": "CCCc1nc2c(c(=O)[nH]1)N(C)C(C)=N2",                             "kind": "best"},
            {"name": "Caffeine",    "desc": "Decoy — weak non-selective PDE inhibitor","smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",                              "kind": "decoy"},
            {"name": "Ibuprofen",   "desc": "Decoy — NSAID",                         "smiles": "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O",                               "kind": "decoy"},
            {"name": "Glucose",     "desc": "Decoy — sugar",                         "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                                    "kind": "decoy"},
        ],
        "off_target": "PDE6 (retina)", "off_target_pdb": "3JWQ",
        "selectivity_data": {
            "Sildenafil": {"pass": True,  "msg": "~10x selective for PDE5 over PDE6. Some report blue-tinted vision."},
            "Vardenafil": {"pass": False, "msg": "Less selective — higher visual side effects."},
        },
        "admet": {
            "Sildenafil": {"MW": 474, "LogP": 1.9, "HBD": 1, "HBA": 11, "RotBonds": 7, "pass": False, "warning": "Slightly exceeds Lipinski HBA (11>10) but still orally bioavailable."},
            "Vardenafil": {"MW": 488, "LogP": 1.8, "HBD": 1, "HBA": 11, "RotBonds": 7, "pass": False, "warning": "Similar profile to sildenafil."},
        },
        "ending": "Mr. Verma reports significant improvement. Mild headache but no visual disturbances.",
    },
    # ── 5. MALARIA ───────────────────────────────────────────────────────────
    {
        "id": 5, "title": "The Mosquito's Curse",
        "disease": "Malaria", "difficulty": "⭐⭐⭐⭐ Advanced",
        "patient": {"name": "Ms. Banerjee", "age": 28, "gender": "Female",
            "condition": "Cyclical fever, chills, anemia after travel to tropical region",
            "history": "Blood smear confirms P. falciparum. Chloroquine-resistant."},
        "stage1_question": "Which enzyme is the classic antifolate target in Plasmodium?",
        "stage1_options": [
            {"text": "Dihydrofolate reductase (DHFR)", "correct": True,  "feedback": "Correct! Pf-DHFR is essential for DNA synthesis. Selective inhibitors spare human DHFR."},
            {"text": "Thymidylate synthase",           "correct": False, "feedback": "Important but DHFR is the primary validated target here."},
            {"text": "Heme polymerase",                "correct": False, "feedback": "That's the chloroquine target — patient is resistant to it."},
            {"text": "Cytochrome bc1",                 "correct": False, "feedback": "Valid for atovaquone, but DHFR is more selective here."},
        ],
        "target_protein": "Pf-DHFR", "target_pdb": "3QGT",
        "pocket_regions": [
            {"name": "NADPH binding site",              "correct": False, "feedback": "Adjacent to substrate pocket but not the primary drug target."},
            {"name": "Folate substrate binding pocket", "correct": True,  "feedback": "Correct! Antifolates compete here. Key residue: Phe58 (vs Ile in human DHFR)."},
            {"name": "Hinge region",                    "correct": False, "feedback": "Moves during catalysis but isn't a drug-binding site."},
            {"name": "Dimerization domain",             "correct": False, "feedback": "Pf-DHFR is a single chain with thymidylate synthase."},
        ],
        "candidates": [
            {"name": "Pyrimethamine", "desc": "Classic antifolate antimalarial",   "smiles": "CCc1nc(N)nc(N)c1-c1ccc(Cl)cc1",             "kind": "best"},
            {"name": "Cycloguanil",   "desc": "Active metabolite of proguanil",    "smiles": "CC1(C)N=C(N)N=C(N)N1c1ccc(Cl)cc1",         "kind": "alt"},
            {"name": "Trimethoprim",  "desc": "Bacterial DHFR inhibitor — weaker","smiles": "COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC",          "kind": "weak"},
            {"name": "Paracetamol",   "desc": "Decoy — fever reducer only",        "smiles": "CC(=O)Nc1ccc(O)cc1",                        "kind": "decoy"},
            {"name": "Quinine",       "desc": "Decoy — different mechanism",       "smiles": "COc1ccc2nccc([C@@H](O)[C@H]3CC[C@@H](C=C)CN3)c2c1", "kind": "decoy"},
            {"name": "Aspirin",       "desc": "Decoy — NSAID",                     "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                  "kind": "decoy"},
        ],
        "off_target": "Human DHFR", "off_target_pdb": "1U72",
        "selectivity_data": {
            "Pyrimethamine": {"pass": True, "msg": "Excellent selectivity! Phe58 in Pf-DHFR vs Ile in human DHFR."},
            "Cycloguanil":   {"pass": True, "msg": "Good selectivity. Watch for resistance mutations."},
        },
        "admet": {
            "Pyrimethamine": {"MW": 248, "LogP": 2.7, "HBD": 2, "HBA": 3, "RotBonds": 2, "pass": True, "warning": "Long-term use causes folate deficiency — co-administer folinic acid."},
            "Cycloguanil":   {"MW": 251, "LogP": 1.9, "HBD": 3, "HBA": 4, "RotBonds": 2, "pass": True, "warning": None},
        },
        "ending": "Ms. Banerjee's fever resolves in 48 hours. Parasitemia clears. Discharged with folate supplement.",
    },
    # ── 6. ASTHMA ────────────────────────────────────────────────────────────
    {
        "id": 6, "title": "Breathless in the City",
        "disease": "Asthma", "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Master Rohan", "age": 14, "gender": "Male",
            "condition": "Acute asthma attack — wheezing, shortness of breath",
            "history": "Triggered by exercise and dust. Needs fast bronchodilator."},
        "stage1_question": "Which receptor, when activated, relaxes airway smooth muscle?",
        "stage1_options": [
            {"text": "β1-adrenergic receptor", "correct": False, "feedback": "β1 is mainly in the heart — activating it causes tachycardia."},
            {"text": "β2-adrenergic receptor", "correct": True,  "feedback": "Correct! β2 on airway smooth muscle causes bronchodilation."},
            {"text": "α1-adrenergic receptor", "correct": False, "feedback": "α1 causes vasoconstriction — wrong target."},
            {"text": "Muscarinic M3 receptor", "correct": False, "feedback": "M3 causes bronchoconstriction — the opposite of what we want!"},
        ],
        "target_protein": "β2-adrenergic receptor", "target_pdb": "2RH1",
        "pocket_regions": [
            {"name": "Orthosteric pocket in TM bundle", "correct": True,  "feedback": "Correct! Agonists bind in the orthosteric site within the 7-TM bundle."},
            {"name": "Extracellular loop ECL2",          "correct": False, "feedback": "ECL2 caps the pocket but isn't the binding site."},
            {"name": "Intracellular G-protein site",     "correct": False, "feedback": "G-proteins bind here, not drugs."},
            {"name": "Membrane lipid surface",           "correct": False, "feedback": "Lipid contact surface — not a drug site."},
        ],
        "candidates": [
            {"name": "Salbutamol",  "desc": "Short-acting β2 agonist (Albuterol)", "smiles": "CC(C)(C)NCC(O)c1ccc(O)c(CO)c1",                    "kind": "best"},
            {"name": "Salmeterol",  "desc": "Long-acting β2 agonist",              "smiles": "OCc1cc(C(O)CNCCCCCCOCCCCc2ccccc2)ccc1O",           "kind": "alt"},
            {"name": "Epinephrine", "desc": "Non-selective adrenergic agonist",    "smiles": "CNCC(O)c1ccc(O)c(O)c1",                             "kind": "weak"},
            {"name": "Propranolol", "desc": "Decoy — β-blocker (worsens asthma!)", "smiles": "CC(C)NCC(O)COc1cccc2ccccc12",                       "kind": "decoy"},
            {"name": "Aspirin",     "desc": "Decoy — can trigger asthma",          "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                          "kind": "decoy"},
            {"name": "Caffeine",    "desc": "Decoy — mild stimulant",              "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",                     "kind": "decoy"},
        ],
        "off_target": "β1-adrenergic receptor", "off_target_pdb": "7BVQ",
        "selectivity_data": {
            "Salbutamol": {"pass": True, "msg": "Good β2 selectivity — minimal cardiac effects at therapeutic dose."},
            "Salmeterol": {"pass": True, "msg": "Highly selective. Long tail anchors for prolonged action."},
        },
        "admet": {
            "Salbutamol": {"MW": 239, "LogP": 0.3, "HBD": 4, "HBA": 4, "RotBonds": 5,  "pass": True,  "warning": None},
            "Salmeterol": {"MW": 415, "LogP": 3.9, "HBD": 4, "HBA": 5, "RotBonds": 15, "pass": False, "warning": "⚠️ Exceeds rotatable bond limit — but inhaled route bypasses oral bioavailability."},
        },
        "ending": "Rohan's wheezing resolves within minutes. Prescribed a rescue inhaler.",
    },
    # ── 7. DEPRESSION ────────────────────────────────────────────────────────
    {
        "id": 7, "title": "Beyond the Blue",
        "disease": "Major Depression", "difficulty": "⭐⭐⭐ Intermediate",
        "patient": {"name": "Ms. Iyer", "age": 34, "gender": "Female",
            "condition": "Persistent low mood, anhedonia, fatigue for 6+ months",
            "history": "Therapy alone insufficient. Needs pharmacological support."},
        "stage1_question": "Depression involves low serotonin. Which protein, if blocked, increases synaptic serotonin?",
        "stage1_options": [
            {"text": "Serotonin receptor 5-HT2A",    "correct": False, "feedback": "5-HT2A is a receptor — blocking it reduces serotonin signalling."},
            {"text": "Serotonin transporter (SERT)", "correct": True,  "feedback": "Correct! SERT removes serotonin from synapses. Blocking it (SSRIs) increases availability."},
            {"text": "Tryptophan hydroxylase",       "correct": False, "feedback": "Makes serotonin — inhibiting it would worsen depression."},
            {"text": "MAO-B",                        "correct": False, "feedback": "MAO-B mainly degrades dopamine, not serotonin."},
        ],
        "target_protein": "SERT", "target_pdb": "5I6X",
        "pocket_regions": [
            {"name": "Central S1 substrate site",    "correct": True,  "feedback": "Correct! SSRIs bind in S1 to block serotonin transport."},
            {"name": "Vestibular S2 allosteric site","correct": False, "feedback": "S2 modulates binding but isn't the primary SSRI site."},
            {"name": "Cytoplasmic C-terminus",       "correct": False, "feedback": "Regulatory region, not a drug binding site."},
            {"name": "Membrane lipid interface",     "correct": False, "feedback": "Lipid contact — not drug binding."},
        ],
        "candidates": [
            {"name": "Fluoxetine",  "desc": "SSRI (Prozac)",              "smiles": "CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1",         "kind": "best"},
            {"name": "Sertraline",  "desc": "SSRI (Zoloft)",              "smiles": "CNC1CCc2cc(-c3ccc(Cl)cc3Cl)cccc21",           "kind": "alt"},
            {"name": "Imipramine",  "desc": "Old tricyclic — less selective","smiles": "CN(C)CCCN1c2ccccc2CCc2ccccc21",            "kind": "weak"},
            {"name": "Caffeine",    "desc": "Decoy — stimulant",          "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",              "kind": "decoy"},
            {"name": "Glucose",     "desc": "Decoy — sugar",              "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                  "kind": "decoy"},
            {"name": "Vitamin D",   "desc": "Decoy — vitamin",            "smiles": "CC(CCCC(C)C)C1CCC2C1(CCCC2=CC=C3CC(O)CCC3=C)C", "kind": "decoy"},
        ],
        "off_target": "NET (Norepinephrine transporter)", "off_target_pdb": "7Y7X",
        "selectivity_data": {
            "Fluoxetine": {"pass": True, "msg": "Selective for SERT over NET — fewer adrenergic side effects."},
            "Sertraline": {"pass": True, "msg": "Most SERT-selective SSRI. Mild dopamine effect adds energizing quality."},
        },
        "admet": {
            "Fluoxetine": {"MW": 309, "LogP": 4.1, "HBD": 1, "HBA": 3, "RotBonds": 6, "pass": True, "warning": "Long half-life (1-3 days) — slow onset and slow washout."},
            "Sertraline": {"MW": 306, "LogP": 5.1, "HBD": 1, "HBA": 2, "RotBonds": 3, "pass": False,"warning": "LogP at upper limit (5.1) — high lipophilicity."},
        },
        "ending": "Ms. Iyer reports improved mood after 6 weeks. Combined with therapy, she's returning to her interests.",
    },
    # ── 8. ALLERGY ───────────────────────────────────────────────────────────
    {
        "id": 8, "title": "The Sneezing Season",
        "disease": "Seasonal Allergy", "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Mrs. Khan", "age": 32, "gender": "Female",
            "condition": "Sneezing, runny nose, itchy eyes during pollen season",
            "history": "Older antihistamines caused drowsiness at work."},
        "stage1_question": "Allergic symptoms are caused by histamine. Which receptor mediates these symptoms?",
        "stage1_options": [
            {"text": "Histamine H1 receptor", "correct": True,  "feedback": "Correct! H1 mediates itching, sneezing, and vasodilation in allergies."},
            {"text": "Histamine H2 receptor", "correct": False, "feedback": "H2 controls stomach acid — wrong target for allergy."},
            {"text": "Adrenergic α1 receptor","correct": False, "feedback": "Used as decongestant but doesn't address the histamine cause."},
            {"text": "Muscarinic M1",          "correct": False, "feedback": "Wrong system entirely."},
        ],
        "target_protein": "Histamine H1 receptor", "target_pdb": "3RZE",
        "pocket_regions": [
            {"name": "Orthosteric site in TM bundle", "correct": True,  "feedback": "Correct! Antihistamines bind where histamine would, blocking activation."},
            {"name": "Intracellular loop ICL3",        "correct": False, "feedback": "G-protein interaction site."},
            {"name": "Extracellular N-terminus",       "correct": False, "feedback": "Not where drugs bind."},
            {"name": "Cytoplasmic tail",               "correct": False, "feedback": "Regulatory phosphorylation site."},
        ],
        "candidates": [
            {"name": "Loratadine",      "desc": "Second-gen non-sedating",   "smiles": "CCOC(=O)N1CCC(=C2c3ccc(Cl)cc3CCc3cccnc32)CC1",  "kind": "best"},
            {"name": "Cetirizine",      "desc": "Second-gen mildly sedating","smiles": "OC(=O)COCCN1CCN(C(c2ccccc2)c2ccc(Cl)cc2)CC1",    "kind": "alt"},
            {"name": "Diphenhydramine", "desc": "First-gen — very sedating", "smiles": "CN(C)CCOC(c1ccccc1)c1ccccc1",                     "kind": "weak"},
            {"name": "Aspirin",         "desc": "Decoy — NSAID",             "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                        "kind": "decoy"},
            {"name": "Caffeine",        "desc": "Decoy — stimulant",         "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",                   "kind": "decoy"},
            {"name": "Glucose",         "desc": "Decoy — sugar",             "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                       "kind": "decoy"},
        ],
        "off_target": "Muscarinic M1 receptor", "off_target_pdb": "5CXV",
        "selectivity_data": {
            "Loratadine": {"pass": True, "msg": "Excellent H1 selectivity — minimal anticholinergic side effects."},
            "Cetirizine": {"pass": True, "msg": "Good selectivity. Doesn't cross blood-brain barrier well — less sedating."},
        },
        "admet": {
            "Loratadine": {"MW": 383, "LogP": 5.2, "HBD": 0, "HBA": 4, "RotBonds": 3, "pass": False, "warning": "LogP slightly over 5 — accepted exception for non-CNS antihistamines."},
            "Cetirizine": {"MW": 389, "LogP": 1.5, "HBD": 1, "HBA": 5, "RotBonds": 8, "pass": True,  "warning": None},
        },
        "ending": "Mrs. Khan works through pollen season without drowsiness. Sneezing resolved.",
    },
    # ── 9. MIGRAINE ──────────────────────────────────────────────────────────
    {
        "id": 9, "title": "Storm in the Head",
        "disease": "Migraine", "difficulty": "⭐⭐⭐ Intermediate",
        "patient": {"name": "Ms. Reddy", "age": 29, "gender": "Female",
            "condition": "Severe throbbing headache with nausea and light sensitivity",
            "history": "Regular painkillers don't work. Needs targeted migraine therapy."},
        "stage1_question": "Migraines involve cranial vasodilation. Which serotonin receptor causes vasoconstriction when activated?",
        "stage1_options": [
            {"text": "5-HT1B receptor", "correct": True,  "feedback": "Correct! Triptans are 5-HT1B agonists — they constrict dilated cranial vessels."},
            {"text": "5-HT2A receptor", "correct": False, "feedback": "5-HT2A causes vasoconstriction elsewhere — not the migraine target."},
            {"text": "5-HT3 receptor",  "correct": False, "feedback": "5-HT3 is involved in nausea, not vasoconstriction."},
            {"text": "5-HT6 receptor",  "correct": False, "feedback": "5-HT6 is a CNS target for cognition — not migraine."},
        ],
        "target_protein": "5-HT1B receptor", "target_pdb": "4IAR",
        "pocket_regions": [
            {"name": "Orthosteric pocket in TM bundle", "correct": True,  "feedback": "Correct! Triptans bind in the orthosteric site of this GPCR."},
            {"name": "Allosteric ECL2 site",            "correct": False, "feedback": "Not the primary binding site for triptans."},
            {"name": "Intracellular tail",              "correct": False, "feedback": "Regulatory region."},
            {"name": "Dimer interface",                 "correct": False, "feedback": "Not relevant for triptan binding."},
        ],
        "candidates": [
            {"name": "Sumatriptan", "desc": "First triptan for migraine",     "smiles": "CNS(=O)(=O)Cc1ccc2[nH]cc(CCN(C)C)c2c1",         "kind": "best"},
            {"name": "Rizatriptan", "desc": "Newer triptan",                  "smiles": "CN(C)CCc1c[nH]c2ccc(Cn3cncn3)cc12",              "kind": "alt"},
            {"name": "Ergotamine",  "desc": "Old vasoconstrictor — broader",  "smiles": "CC1(CC2CC3=C(C2N1C(=O)C4CCCN4)NC5=CC=CC=C53)CO", "kind": "weak"},
            {"name": "Aspirin",     "desc": "Decoy — basic painkiller",       "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                       "kind": "decoy"},
            {"name": "Caffeine",    "desc": "Decoy — mild vasoconstrictor",   "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",                  "kind": "decoy"},
            {"name": "Glucose",     "desc": "Decoy — sugar",                  "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                      "kind": "decoy"},
        ],
        "off_target": "5-HT2B receptor", "off_target_pdb": "4IB4",
        "selectivity_data": {
            "Sumatriptan": {"pass": True, "msg": "Good selectivity. Some coronary vasoconstriction risk in heart patients."},
            "Rizatriptan": {"pass": True, "msg": "Improved selectivity and faster onset than sumatriptan."},
        },
        "admet": {
            "Sumatriptan": {"MW": 295, "LogP": 1.0, "HBD": 2, "HBA": 4, "RotBonds": 5, "pass": True, "warning": "Avoid in patients with coronary artery disease."},
            "Rizatriptan": {"MW": 269, "LogP": 1.7, "HBD": 1, "HBA": 5, "RotBonds": 4, "pass": True, "warning": None},
        },
        "ending": "Ms. Reddy's headache resolves in an hour. Now keeps triptans for acute episodes.",
    },
    # ── 10. PARKINSON'S ──────────────────────────────────────────────────────
    {
        "id": 10, "title": "Trembling Hands",
        "disease": "Parkinson's Disease", "difficulty": "⭐⭐⭐⭐ Advanced",
        "patient": {"name": "Mr. Joshi", "age": 68, "gender": "Male",
            "condition": "Resting tremor, rigidity, slow movements",
            "history": "Levodopa starting to wear off between doses."},
        "stage1_question": "Parkinson's involves dopamine loss. Which enzyme degrades dopamine in the brain?",
        "stage1_options": [
            {"text": "MAO-A", "correct": False, "feedback": "MAO-A mainly degrades serotonin and norepinephrine."},
            {"text": "MAO-B", "correct": True,  "feedback": "Correct! MAO-B preferentially degrades dopamine in the brain."},
            {"text": "Tyrosine hydroxylase", "correct": False, "feedback": "Tyrosine hydroxylase MAKES dopamine — inhibiting it worsens disease."},
            {"text": "DOPA decarboxylase",   "correct": False, "feedback": "Converts L-DOPA to dopamine — needed for production."},
        ],
        "target_protein": "MAO-B", "target_pdb": "2BYB",
        "pocket_regions": [
            {"name": "FAD-containing active site", "correct": True,  "feedback": "Correct! MAO-B has FAD cofactor at the site where substrate is oxidized."},
            {"name": "Membrane anchor",            "correct": False, "feedback": "Anchors MAO-B to outer mitochondrial membrane."},
            {"name": "Entrance loop",              "correct": False, "feedback": "Substrate channel, not the catalytic site itself."},
            {"name": "Dimer interface",            "correct": False, "feedback": "Where two MAO-B subunits meet."},
        ],
        "candidates": [
            {"name": "Selegiline",  "desc": "Selective MAO-B inhibitor",        "smiles": "CC(Cc1ccccc1)N(C)CC#C",                  "kind": "best"},
            {"name": "Rasagiline",  "desc": "Newer MAO-B inhibitor",            "smiles": "C#CCNC1CCc2ccccc21",                     "kind": "alt"},
            {"name": "Phenelzine",  "desc": "Non-selective MAO inhibitor",      "smiles": "NNCCc1ccccc1",                           "kind": "weak"},
            {"name": "Levodopa",    "desc": "Decoy — dopamine precursor",       "smiles": "NC(Cc1ccc(O)c(O)c1)C(=O)O",             "kind": "decoy"},
            {"name": "Aspirin",     "desc": "Decoy — NSAID",                    "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",              "kind": "decoy"},
            {"name": "Glucose",     "desc": "Decoy — sugar",                    "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",             "kind": "decoy"},
        ],
        "off_target": "MAO-A", "off_target_pdb": "2Z5X",
        "selectivity_data": {
            "Selegiline": {"pass": True, "msg": "MAO-B selective at low doses. Avoid tyramine-rich foods at high doses."},
            "Rasagiline": {"pass": True, "msg": "Highly selective for MAO-B — safer cheese reaction profile."},
        },
        "admet": {
            "Selegiline": {"MW": 187, "LogP": 2.9, "HBD": 0, "HBA": 1, "RotBonds": 3, "pass": True, "warning": "Avoid aged cheeses — risk of hypertensive crisis at high doses."},
            "Rasagiline": {"MW": 171, "LogP": 2.3, "HBD": 1, "HBA": 1, "RotBonds": 1, "pass": True, "warning": None},
        },
        "ending": "Mr. Joshi's tremor reduces. Movements smoother throughout the day.",
    },
    # ── 11. EPILEPSY ─────────────────────────────────────────────────────────
    {
        "id": 11, "title": "Electric Storm",
        "disease": "Epilepsy", "difficulty": "⭐⭐⭐ Intermediate",
        "patient": {"name": "Master Arjun", "age": 16, "gender": "Male",
            "condition": "Recurrent tonic-clonic seizures",
            "history": "Recent diagnosis. Needs first-line antiepileptic."},
        "stage1_question": "Seizures involve excessive neuronal firing. Which ion channel, if blocked, reduces excitability?",
        "stage1_options": [
            {"text": "Voltage-gated Na+ channel",    "correct": True,  "feedback": "Correct! Blocking Na+ channels prevents the rapid firing that causes seizures."},
            {"text": "Voltage-gated K+ channel",     "correct": False, "feedback": "K+ channels repolarize neurons — blocking them worsens seizures."},
            {"text": "Calcium-activated K+ channel", "correct": False, "feedback": "Not the standard seizure target."},
            {"text": "Aquaporin",                    "correct": False, "feedback": "Water channel — unrelated to seizures."},
        ],
        "target_protein": "Nav1.2 (Na+ channel)", "target_pdb": "6J8E",
        "pocket_regions": [
            {"name": "Inactivation gate (DIV-S6)", "correct": True,  "feedback": "Correct! Most antiepileptics bind near the inactivation gate, stabilizing the closed state."},
            {"name": "Voltage sensor",             "correct": False, "feedback": "Senses membrane voltage but isn't the typical drug site."},
            {"name": "Selectivity filter",         "correct": False, "feedback": "Controls ion selectivity — not where AEDs bind."},
            {"name": "Cytoplasmic loop",           "correct": False, "feedback": "Regulatory region."},
        ],
        "candidates": [
            {"name": "Phenytoin",    "desc": "Classic Na+ channel blocker",    "smiles": "O=C1NC(=O)C(c2ccccc2)(c2ccccc2)N1",  "kind": "best"},
            {"name": "Carbamazepine","desc": "Na+ channel blocker, broad use", "smiles": "NC(=O)N1c2ccccc2C=Cc2ccccc21",        "kind": "alt"},
            {"name": "Lamotrigine",  "desc": "Newer Na+ channel modulator",   "smiles": "Nc1nnc(-c2cccc(Cl)c2Cl)c(N)n1",      "kind": "alt"},
            {"name": "Aspirin",      "desc": "Decoy — NSAID",                  "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",           "kind": "decoy"},
            {"name": "Caffeine",     "desc": "Decoy — can worsen seizures",    "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",      "kind": "decoy"},
            {"name": "Glucose",      "desc": "Decoy — sugar",                  "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",          "kind": "decoy"},
        ],
        "off_target": "Cardiac Nav1.5", "off_target_pdb": "6UZ3",
        "selectivity_data": {
            "Phenytoin":    {"pass": True, "msg": "Modest selectivity — IV phenytoin must be slow to avoid arrhythmia."},
            "Carbamazepine":{"pass": True, "msg": "Better cardiac safety profile than phenytoin."},
            "Lamotrigine":  {"pass": True, "msg": "Cleanest profile — minimal cardiac effects."},
        },
        "admet": {
            "Phenytoin":    {"MW": 252, "LogP": 2.5, "HBD": 2, "HBA": 2, "RotBonds": 2, "pass": True, "warning": "Narrow therapeutic window — requires plasma level monitoring."},
            "Carbamazepine":{"MW": 236, "LogP": 2.5, "HBD": 1, "HBA": 1, "RotBonds": 0, "pass": True, "warning": "Auto-induces CYP3A4 — dose adjustment needed."},
            "Lamotrigine":  {"MW": 256, "LogP": 1.9, "HBD": 2, "HBA": 4, "RotBonds": 1, "pass": True, "warning": "Slow titration needed to avoid Stevens-Johnson syndrome."},
        },
        "ending": "Arjun has been seizure-free for 6 months. Back to school and cricket.",
    },
    # ── 12. BACTERIAL UTI ────────────────────────────────────────────────────
    {
        "id": 12, "title": "Invisible Invaders",
        "disease": "Bacterial UTI", "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Mrs. Pillai", "age": 41, "gender": "Female",
            "condition": "Burning urination, fever — UTI confirmed by culture",
            "history": "E. coli isolated, sensitive to fluoroquinolones."},
        "stage1_question": "Which bacterial enzyme unwinds DNA for replication — a key antibiotic target?",
        "stage1_options": [
            {"text": "DNA polymerase III",        "correct": False, "feedback": "Replicates DNA but not the classic fluoroquinolone target."},
            {"text": "DNA gyrase (Topoisomerase II)","correct": True,"feedback": "Correct! Fluoroquinolones inhibit DNA gyrase, blocking supercoil relaxation."},
            {"text": "Ribosome 30S subunit",      "correct": False, "feedback": "That's the aminoglycoside target for protein synthesis."},
            {"text": "Cell wall transpeptidase",  "correct": False, "feedback": "That's the penicillin target for cell wall synthesis."},
        ],
        "target_protein": "Bacterial DNA gyrase", "target_pdb": "2XCT",
        "pocket_regions": [
            {"name": "DNA-cleavage interface", "correct": True,  "feedback": "Correct! Fluoroquinolones bind here, trapping cut DNA."},
            {"name": "ATP binding domain",     "correct": False, "feedback": "ATP binds for energy, not where fluoroquinolones act."},
            {"name": "C-terminal domain",      "correct": False, "feedback": "DNA wrapping function — not drug binding."},
            {"name": "Coiled-coil region",     "correct": False, "feedback": "Structural element."},
        ],
        "candidates": [
            {"name": "Ciprofloxacin", "desc": "Second-gen fluoroquinolone",   "smiles": "O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O", "kind": "best"},
            {"name": "Levofloxacin",  "desc": "Third-gen fluoroquinolone",    "smiles": "CC1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23", "kind": "alt"},
            {"name": "Nalidixic acid","desc": "First-gen quinolone — weaker", "smiles": "CCN1C=C(C(=O)O)C(=O)c2cc(C)ncc21",             "kind": "weak"},
            {"name": "Paracetamol",   "desc": "Decoy — painkiller",           "smiles": "CC(=O)Nc1ccc(O)cc1",                           "kind": "decoy"},
            {"name": "Aspirin",       "desc": "Decoy — NSAID",                "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                     "kind": "decoy"},
            {"name": "Glucose",       "desc": "Decoy — sugar",                "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                    "kind": "decoy"},
        ],
        "off_target": "Human Topoisomerase II", "off_target_pdb": "4FM9",
        "selectivity_data": {
            "Ciprofloxacin": {"pass": True, "msg": "Good selectivity for bacterial vs human enzyme. Side effects include tendon issues."},
            "Levofloxacin":  {"pass": True, "msg": "Improved spectrum and once-daily dosing."},
        },
        "admet": {
            "Ciprofloxacin": {"MW": 331, "LogP": 0.3,  "HBD": 2, "HBA": 5, "RotBonds": 3, "pass": True, "warning": "Avoid in growing children — affects cartilage. QT prolongation risk."},
            "Levofloxacin":  {"MW": 361, "LogP": -0.4, "HBD": 1, "HBA": 6, "RotBonds": 2, "pass": True, "warning": "Tendon rupture risk in elderly."},
        },
        "ending": "Mrs. Pillai recovers in 3 days. Urine culture confirms bacterial clearance.",
    },
    # ── 13. TUBERCULOSIS ─────────────────────────────────────────────────────
    {
        "id": 13, "title": "The Silent Killer Returns",
        "disease": "Tuberculosis", "difficulty": "⭐⭐⭐⭐ Advanced",
        "patient": {"name": "Mr. Das", "age": 38, "gender": "Male",
            "condition": "Persistent cough, weight loss, night sweats — TB confirmed",
            "history": "Drug-sensitive M. tuberculosis. Needs first-line regimen."},
        "stage1_question": "Which enzyme makes mycolic acids — the unique cell wall component of M. tuberculosis?",
        "stage1_options": [
            {"text": "InhA (enoyl-ACP reductase)", "correct": True,  "feedback": "Correct! InhA is essential for mycolic acid synthesis — the target of isoniazid."},
            {"text": "Penicillin-binding protein", "correct": False, "feedback": "Standard bacterial cell wall — not unique to TB."},
            {"text": "Topoisomerase II",           "correct": False, "feedback": "DNA target — fluoroquinolones, not first-line TB."},
            {"text": "RNA polymerase",             "correct": False, "feedback": "That's the rifampicin target — separate pathway."},
        ],
        "target_protein": "InhA", "target_pdb": "2X23",
        "pocket_regions": [
            {"name": "NAD(H) binding site",  "correct": True,  "feedback": "Correct! Isoniazid forms an adduct with NAD at this site."},
            {"name": "Substrate channel",    "correct": False, "feedback": "Where fatty acid substrates pass through."},
            {"name": "Dimer interface",      "correct": False, "feedback": "Where InhA tetramerizes."},
            {"name": "C-terminal tail",      "correct": False, "feedback": "Regulatory region."},
        ],
        "candidates": [
            {"name": "Isoniazid",    "desc": "First-line TB drug (prodrug)",       "smiles": "NNC(=O)c1ccncc1",                "kind": "best"},
            {"name": "Ethionamide",  "desc": "Second-line, similar mechanism",     "smiles": "CCc1cc(C(N)=S)ccn1",             "kind": "alt"},
            {"name": "Pyrazinamide", "desc": "Different mechanism — fatty acid",   "smiles": "NC(=O)c1cnccn1",                 "kind": "weak"},
            {"name": "Aspirin",      "desc": "Decoy — NSAID",                      "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",      "kind": "decoy"},
            {"name": "Glucose",      "desc": "Decoy — sugar",                      "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",     "kind": "decoy"},
            {"name": "Caffeine",     "desc": "Decoy — stimulant",                  "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C", "kind": "decoy"},
        ],
        "off_target": "Human MAO", "off_target_pdb": "2Z5X",
        "selectivity_data": {
            "Isoniazid":   {"pass": True, "msg": "Selective for InhA but also inhibits human MAO — drug-food interactions possible."},
            "Ethionamide": {"pass": True, "msg": "Similar selectivity but more GI side effects."},
        },
        "admet": {
            "Isoniazid":   {"MW": 137, "LogP": -0.7, "HBD": 3, "HBA": 3, "RotBonds": 1, "pass": True, "warning": "⚠️ Hepatotoxicity — monitor liver function. Pyridoxine prevents neuropathy."},
            "Ethionamide": {"MW": 166, "LogP": 0.5,  "HBD": 1, "HBA": 2, "RotBonds": 1, "pass": True, "warning": "Severe GI side effects limit use."},
        },
        "ending": "Mr. Das completes 6 months of therapy. Sputum cultures clear. Disease cured.",
    },
    # ── 14. INFLUENZA ────────────────────────────────────────────────────────
    {
        "id": 14, "title": "The Flu Season",
        "disease": "Influenza", "difficulty": "⭐⭐⭐ Intermediate",
        "patient": {"name": "Mr. Kapoor", "age": 45, "gender": "Male",
            "condition": "Sudden fever, body aches, dry cough — influenza A confirmed",
            "history": "Diagnosed within 48 hours. Antiviral indicated."},
        "stage1_question": "Influenza uses an enzyme to escape infected cells. What is it?",
        "stage1_options": [
            {"text": "Hemagglutinin",  "correct": False, "feedback": "Hemagglutinin is for cell entry, not escape."},
            {"text": "Neuraminidase",  "correct": True,  "feedback": "Correct! Neuraminidase cleaves sialic acid so new virus particles can escape."},
            {"text": "RNA polymerase", "correct": False, "feedback": "Replicates viral RNA but isn't the oseltamivir target."},
            {"text": "M2 ion channel", "correct": False, "feedback": "M2 is the amantadine target — now universally resistant."},
        ],
        "target_protein": "Influenza Neuraminidase", "target_pdb": "2HU4",
        "pocket_regions": [
            {"name": "Sialic acid binding pocket", "correct": True,  "feedback": "Correct! Oseltamivir mimics sialic acid and blocks this pocket."},
            {"name": "Calcium binding loop",       "correct": False, "feedback": "Structural role, not where drugs bind."},
            {"name": "Membrane anchor",            "correct": False, "feedback": "Attaches neuraminidase to viral envelope."},
            {"name": "Tetramerization interface",  "correct": False, "feedback": "Where four NA subunits meet."},
        ],
        "candidates": [
            {"name": "Oseltamivir","desc": "Oral neuraminidase inhibitor (Tamiflu)","smiles": "CCOC(=O)C1=C[C@@H](OC(CC)CC)[C@@H](NC(C)=O)[C@@H](N)C1", "kind": "best"},
            {"name": "Zanamivir", "desc": "Inhaled neuraminidase inhibitor",        "smiles": "CC(=O)N[C@@H]1[C@H](O)C=C(C(=O)O)O[C@H]1[C@H](O)[C@H](O)CO", "kind": "alt"},
            {"name": "Amantadine","desc": "Old M2 blocker — universal resistance", "smiles": "NC12CC3CC(CC(C3)C1)C2",                                    "kind": "weak"},
            {"name": "Paracetamol","desc": "Decoy — fever reducer only",           "smiles": "CC(=O)Nc1ccc(O)cc1",                                       "kind": "decoy"},
            {"name": "Aspirin",   "desc": "Decoy — NSAID",                          "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                                "kind": "decoy"},
            {"name": "Glucose",   "desc": "Decoy — sugar",                          "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                               "kind": "decoy"},
        ],
        "off_target": "Human Sialidase NEU2", "off_target_pdb": "1VCU",
        "selectivity_data": {
            "Oseltamivir": {"pass": True, "msg": "Excellent selectivity for viral over human sialidase."},
            "Zanamivir":   {"pass": True, "msg": "Even better selectivity, but inhaled only — limited bioavailability."},
        },
        "admet": {
            "Oseltamivir": {"MW": 312, "LogP": 0.9,  "HBD": 2, "HBA": 5, "RotBonds": 7, "pass": True,  "warning": "Prodrug — activated by hepatic esterases. Rare neuropsychiatric events."},
            "Zanamivir":   {"MW": 332, "LogP": -2.7, "HBD": 7, "HBA": 8, "RotBonds": 7, "pass": False, "warning": "Too polar for oral absorption — inhalation only."},
        },
        "ending": "Mr. Kapoor's fever breaks in 24 hours. Recovers in 4 days instead of a week.",
    },
    # ── 15. HIV ──────────────────────────────────────────────────────────────
    {
        "id": 15, "title": "The Persistent Virus",
        "disease": "HIV Infection", "difficulty": "⭐⭐⭐⭐ Advanced",
        "patient": {"name": "Mr. Anonymous", "age": 35, "gender": "Male",
            "condition": "Newly diagnosed HIV-positive, high viral load",
            "history": "Starting first-line antiretroviral therapy (ART)."},
        "stage1_question": "HIV is a retrovirus. Which enzyme converts its RNA into DNA?",
        "stage1_options": [
            {"text": "Reverse transcriptase (RT)", "correct": True,  "feedback": "Correct! RT is unique to retroviruses — a key antiretroviral target."},
            {"text": "Protease",                   "correct": False, "feedback": "Protease is also targeted but acts later — cleaving viral proteins."},
            {"text": "Integrase",                  "correct": False, "feedback": "Integrase inserts viral DNA into the host genome — a separate step."},
            {"text": "Helicase",                   "correct": False, "feedback": "Not a primary HIV drug target."},
        ],
        "target_protein": "HIV-1 Reverse Transcriptase", "target_pdb": "1FK9",
        "pocket_regions": [
            {"name": "NNRTI allosteric pocket",  "correct": True,  "feedback": "Correct! NNRTIs bind a hydrophobic pocket allosteric to the active site."},
            {"name": "RNase H domain",           "correct": False, "feedback": "Important for function but not the NNRTI binding site."},
            {"name": "Connection domain",        "correct": False, "feedback": "Structural role."},
            {"name": "p51 subunit interface",    "correct": False, "feedback": "Where the two RT subunits meet."},
        ],
        "candidates": [
            {"name": "Efavirenz",       "desc": "First-line NNRTI",           "smiles": "O=C1Oc2ccc(Cl)cc2[C@@](C#CC2CC2)(C(F)(F)F)N1", "kind": "best"},
            {"name": "Nevirapine",      "desc": "Older NNRTI",                "smiles": "Cc1ccnc2c1Nc1cccnc1C(=O)N2C1CC1",              "kind": "alt"},
            {"name": "Zidovudine (AZT)","desc": "NRTI — different mechanism", "smiles": "Cc1cn([C@H]2C[C@H](N=[N+]=[N-])[C@@H](CO)O2)c(=O)[nH]c1=O", "kind": "weak"},
            {"name": "Aspirin",         "desc": "Decoy — NSAID",              "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                     "kind": "decoy"},
            {"name": "Vitamin C",       "desc": "Decoy — supplement",         "smiles": "C(C(C1C(=C(C(=O)O1)O)O)O)O",                   "kind": "decoy"},
            {"name": "Glucose",         "desc": "Decoy — sugar",              "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                    "kind": "decoy"},
        ],
        "off_target": "hERG K+ channel", "off_target_pdb": "5VA1",
        "selectivity_data": {
            "Efavirenz": {"pass": True, "msg": "Good cardiac safety. Main side effects: CNS (vivid dreams, dizziness)."},
            "Nevirapine": {"pass": True, "msg": "Good cardiac profile but liver toxicity risk."},
        },
        "admet": {
            "Efavirenz": {"MW": 316, "LogP": 4.7, "HBD": 1, "HBA": 4, "RotBonds": 2, "pass": True, "warning": "Take at bedtime — CNS side effects more tolerable during sleep."},
            "Nevirapine": {"MW": 266, "LogP": 1.8, "HBD": 1, "HBA": 4, "RotBonds": 1, "pass": True, "warning": "⚠️ Hepatotoxicity and Stevens-Johnson syndrome — slow titration required."},
        },
        "ending": "Viral load undetectable in 6 months. Mr. Anonymous on lifelong ART with normal life expectancy.",
    },
    # ── 16. GLAUCOMA ─────────────────────────────────────────────────────────
    {
        "id": 16, "title": "Pressure in the Eye",
        "disease": "Glaucoma", "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Mrs. Mehta", "age": 60, "gender": "Female",
            "condition": "Elevated intraocular pressure, gradual peripheral vision loss",
            "history": "Open-angle glaucoma. Needs to reduce aqueous humor production."},
        "stage1_question": "Aqueous humor production needs bicarbonate. Which enzyme produces it?",
        "stage1_options": [
            {"text": "Carbonic anhydrase II", "correct": True,  "feedback": "Correct! CA-II in ciliary body makes bicarbonate. Inhibiting it reduces aqueous humor."},
            {"text": "Acetylcholinesterase",  "correct": False, "feedback": "Wrong target — pilocarpine acts via muscarinic receptors."},
            {"text": "Adenylyl cyclase",      "correct": False, "feedback": "Not the glaucoma target."},
            {"text": "Aldose reductase",      "correct": False, "feedback": "Involved in diabetic eye disease, not glaucoma."},
        ],
        "target_protein": "Carbonic Anhydrase II", "target_pdb": "4M2U",
        "pocket_regions": [
            {"name": "Zinc-containing active site", "correct": True,  "feedback": "Correct! CA has Zn²⁺ at the active site. Sulfonamide drugs coordinate this zinc."},
            {"name": "Surface helix",              "correct": False, "feedback": "Not catalytic."},
            {"name": "Dimer interface",            "correct": False, "feedback": "CA-II is monomeric."},
            {"name": "Membrane anchor",            "correct": False, "feedback": "CA-II is cytoplasmic."},
        ],
        "candidates": [
            {"name": "Dorzolamide",   "desc": "Topical CA inhibitor",           "smiles": "CCN[C@H]1C[C@H](C)S(=O)(=O)c2sc(S(N)(=O)=O)cc21",  "kind": "best"},
            {"name": "Brinzolamide",  "desc": "Newer topical CA inhibitor",     "smiles": "CCNC1CN(CCOC)S(=O)(=O)c2sc(S(N)(=O)=O)cc21",       "kind": "alt"},
            {"name": "Acetazolamide", "desc": "Oral CA inhibitor — more side effects","smiles": "CC(=O)NC1=NN=C(S1)S(=O)(=O)N",              "kind": "weak"},
            {"name": "Aspirin",       "desc": "Decoy — NSAID",                   "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                         "kind": "decoy"},
            {"name": "Caffeine",      "desc": "Decoy — stimulant",               "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",                    "kind": "decoy"},
            {"name": "Glucose",       "desc": "Decoy — sugar",                   "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                        "kind": "decoy"},
        ],
        "off_target": "Carbonic Anhydrase I", "off_target_pdb": "1HCB",
        "selectivity_data": {
            "Dorzolamide":  {"pass": True, "msg": "Good CA-II selectivity. Topical use limits systemic absorption."},
            "Brinzolamide": {"pass": True, "msg": "Less stinging than dorzolamide — better tolerated."},
        },
        "admet": {
            "Dorzolamide":  {"MW": 324, "LogP": 0.7, "HBD": 2, "HBA": 6, "RotBonds": 4, "pass": True, "warning": "Eye stinging common. Avoid in sulfa-allergic patients."},
            "Brinzolamide": {"MW": 383, "LogP": 0.4, "HBD": 2, "HBA": 7, "RotBonds": 5, "pass": True, "warning": None},
        },
        "ending": "Mrs. Mehta's intraocular pressure normalizes. Vision loss halted with regular eye drops.",
    },
    # ── 17. SCHIZOPHRENIA ────────────────────────────────────────────────────
    {
        "id": 17, "title": "Shattered Reality",
        "disease": "Schizophrenia", "difficulty": "⭐⭐⭐⭐ Advanced",
        "patient": {"name": "Mr. Anonymous", "age": 24, "gender": "Male",
            "condition": "Auditory hallucinations, paranoid delusions, disorganized thinking",
            "history": "First psychotic episode. Needs antipsychotic therapy."},
        "stage1_question": "Schizophrenia involves dopamine hyperactivity. Which receptor do all antipsychotics block?",
        "stage1_options": [
            {"text": "Dopamine D1 receptor", "correct": False, "feedback": "D1 isn't the primary antipsychotic target."},
            {"text": "Dopamine D2 receptor", "correct": True,  "feedback": "Correct! D2 blockade in the mesolimbic pathway reduces positive symptoms."},
            {"text": "Serotonin 5-HT3",      "correct": False, "feedback": "Involved in nausea, not psychosis."},
            {"text": "Glutamate NMDA",        "correct": False, "feedback": "Theory involves NMDA but it's not the standard drug target."},
        ],
        "target_protein": "Dopamine D2 receptor", "target_pdb": "6CM4",
        "pocket_regions": [
            {"name": "Orthosteric pocket in TM bundle", "correct": True,  "feedback": "Correct! Antipsychotics bind in the orthosteric site to block dopamine."},
            {"name": "Allosteric extracellular site",   "correct": False, "feedback": "Not the primary binding site for current drugs."},
            {"name": "G-protein interface",             "correct": False, "feedback": "Where signaling proteins bind."},
            {"name": "Lipid interface",                 "correct": False, "feedback": "Membrane contact, not drug binding."},
        ],
        "candidates": [
            {"name": "Haloperidol",    "desc": "Typical antipsychotic — strong D2",      "smiles": "O=C(CCCN1CCC(O)(c2ccc(Cl)cc2)CC1)c1ccc(F)cc1",              "kind": "best"},
            {"name": "Risperidone",    "desc": "Atypical antipsychotic — D2 + 5-HT2A",  "smiles": "Cc1c(CCN2CCC(c3noc4cc(F)ccc34)CC2)c(=O)n2CCCCc2n1",        "kind": "alt"},
            {"name": "Chlorpromazine", "desc": "First antipsychotic — many side effects","smiles": "CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc21",                          "kind": "weak"},
            {"name": "Aspirin",        "desc": "Decoy — NSAID",                          "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                                  "kind": "decoy"},
            {"name": "Caffeine",       "desc": "Decoy — stimulant",                      "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",                             "kind": "decoy"},
            {"name": "Glucose",        "desc": "Decoy — sugar",                          "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                                "kind": "decoy"},
        ],
        "off_target": "5-HT2A receptor", "off_target_pdb": "6A93",
        "selectivity_data": {
            "Haloperidol": {"pass": True, "msg": "Strong D2 selectivity → powerful antipsychotic but high EPS risk."},
            "Risperidone": {"pass": True, "msg": "Balanced D2/5-HT2A blockade → fewer movement side effects."},
        },
        "admet": {
            "Haloperidol": {"MW": 376, "LogP": 4.3, "HBD": 1, "HBA": 3, "RotBonds": 6, "pass": True, "warning": "⚠️ Extrapyramidal symptoms common — risk of tardive dyskinesia."},
            "Risperidone": {"MW": 410, "LogP": 3.5, "HBD": 0, "HBA": 6, "RotBonds": 4, "pass": True, "warning": "Weight gain and metabolic effects common with atypicals."},
        },
        "ending": "Hallucinations subside after 4 weeks. Patient enrolled in therapy and family support.",
    },
    # ── 18. GOUT ─────────────────────────────────────────────────────────────
    {
        "id": 18, "title": "The Painful Joint",
        "disease": "Gout", "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Mr. Bhatt", "age": 55, "gender": "Male",
            "condition": "Sudden severe pain in big toe, red and swollen joint",
            "history": "Serum uric acid elevated. Diet rich in purines."},
        "stage1_question": "Gout is caused by uric acid crystals. Which enzyme MAKES uric acid?",
        "stage1_options": [
            {"text": "Xanthine oxidase",    "correct": True,  "feedback": "Correct! Xanthine oxidase converts xanthine to uric acid. Block it to lower uric acid."},
            {"text": "Adenosine deaminase", "correct": False, "feedback": "Earlier in purine metabolism, but not the gout target."},
            {"text": "PRPP synthetase",     "correct": False, "feedback": "Increases purine production — xanthine oxidase is the better target."},
            {"text": "Uricase",             "correct": False, "feedback": "Uricase DEGRADES uric acid — humans lack it. Activating it would help, not inhibiting."},
        ],
        "target_protein": "Xanthine Oxidase", "target_pdb": "1FIQ",
        "pocket_regions": [
            {"name": "Molybdenum-containing active site", "correct": True,  "feedback": "Correct! The Mo cofactor catalyzes xanthine oxidation. Drugs target this site."},
            {"name": "FAD binding domain",               "correct": False, "feedback": "Electron transfer site, not where xanthine binds."},
            {"name": "[2Fe-2S] cluster",                 "correct": False, "feedback": "Electron relay, not the catalytic site."},
            {"name": "Dimer interface",                  "correct": False, "feedback": "Structural role."},
        ],
        "candidates": [
            {"name": "Allopurinol",  "desc": "First-line xanthine oxidase inhibitor",   "smiles": "O=c1[nH]cnc2[nH]ncc12",                          "kind": "best"},
            {"name": "Febuxostat",   "desc": "Newer non-purine inhibitor",              "smiles": "Cc1nc(-c2ccc(OCC(C)C)c(C#N)c2)sc1C(=O)O",       "kind": "alt"},
            {"name": "Colchicine",   "desc": "Different mechanism — anti-inflammatory","smiles": "COc1cc2c(cc1OC)-c1ccc(=O)c(OC)cc1C(NC(C)=O)CC2", "kind": "weak"},
            {"name": "Aspirin",      "desc": "Decoy — paradoxically WORSENS gout",     "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",                      "kind": "decoy"},
            {"name": "Vitamin C",    "desc": "Decoy — supplement",                     "smiles": "C(C(C1C(=C(C(=O)O1)O)O)O)O",                    "kind": "decoy"},
            {"name": "Glucose",      "desc": "Decoy — sugar",                          "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                     "kind": "decoy"},
        ],
        "off_target": "Aldehyde Oxidase", "off_target_pdb": "4UHX",
        "selectivity_data": {
            "Allopurinol": {"pass": True, "msg": "Selective enough, but hypersensitivity reactions can be severe."},
            "Febuxostat":  {"pass": True, "msg": "Better selectivity. Cardiovascular risk in heart disease patients."},
        },
        "admet": {
            "Allopurinol": {"MW": 136, "LogP": -0.6, "HBD": 2, "HBA": 4, "RotBonds": 0, "pass": True, "warning": "⚠️ Rare severe hypersensitivity (SCAR) — screen HLA-B*5801 in Asian patients."},
            "Febuxostat":  {"MW": 316, "LogP": 3.8,  "HBD": 1, "HBA": 4, "RotBonds": 6, "pass": True, "warning": "FDA black box for cardiovascular events — caution in heart disease."},
        },
        "ending": "Mr. Bhatt's uric acid normalizes in weeks. No more gout flares with dietary changes plus allopurinol.",
    },
    # ── 19. GERD ─────────────────────────────────────────────────────────────
    {
        "id": 19, "title": "The Burning Stomach",
        "disease": "GERD / Peptic Ulcer", "difficulty": "⭐⭐ Beginner",
        "patient": {"name": "Mrs. Roy", "age": 47, "gender": "Female",
            "condition": "Heartburn, acid regurgitation, epigastric pain",
            "history": "Endoscopy shows esophageal erosions. H. pylori negative."},
        "stage1_question": "Stomach acid is secreted by which enzyme in parietal cells?",
        "stage1_options": [
            {"text": "H+/K+ ATPase (proton pump)", "correct": True,  "feedback": "Correct! The proton pump is the final step in acid secretion — the PPI target."},
            {"text": "Na+/K+ ATPase",              "correct": False, "feedback": "Maintains cellular ion balance, not acid secretion."},
            {"text": "Histamine H2 receptor",      "correct": False, "feedback": "Important upstream regulator but PPIs are more effective."},
            {"text": "Carbonic anhydrase",         "correct": False, "feedback": "Provides bicarbonate but not the main acid enzyme."},
        ],
        "target_protein": "H+/K+ ATPase", "target_pdb": "5YLU",
        "pocket_regions": [
            {"name": "Luminal cysteine residues", "correct": True,  "feedback": "Correct! PPIs are activated by acid and form covalent bonds with luminal cysteines."},
            {"name": "ATP binding domain",        "correct": False, "feedback": "Energy source for pumping, not where PPIs act."},
            {"name": "Cytoplasmic loops",         "correct": False, "feedback": "Regulatory, not drug binding."},
            {"name": "Membrane spanning helices", "correct": False, "feedback": "Structural elements."},
        ],
        "candidates": [
            {"name": "Omeprazole",  "desc": "First PPI",       "smiles": "COc1ccc2[nH]c(S(=O)Cc3ncc(C)c(OC)c3C)nc2c1",   "kind": "best"},
            {"name": "Pantoprazole","desc": "Modern PPI",      "smiles": "COc1ccc2nc(S(=O)Cc3nccc(OC)c3OC)[nH]c2c1",     "kind": "alt"},
            {"name": "Ranitidine",  "desc": "H2 blocker — older","smiles": "CNC(=Cc1ccc(s1)CSCCNC(=NCNO)NC)C",           "kind": "weak"},
            {"name": "Aspirin",     "desc": "Decoy — WORSENS ulcers","smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",               "kind": "decoy"},
            {"name": "Caffeine",    "desc": "Decoy — increases acid","smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",           "kind": "decoy"},
            {"name": "Glucose",     "desc": "Decoy — sugar",   "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                    "kind": "decoy"},
        ],
        "off_target": "Na+/K+ ATPase", "off_target_pdb": "2ZXE",
        "selectivity_data": {
            "Omeprazole":   {"pass": True, "msg": "Excellent selectivity. Long-term use linked to B12 and Mg deficiency."},
            "Pantoprazole": {"pass": True, "msg": "Fewer drug interactions than omeprazole."},
        },
        "admet": {
            "Omeprazole":   {"MW": 345, "LogP": 2.2, "HBD": 1, "HBA": 6, "RotBonds": 5, "pass": True, "warning": "Long-term use linked to vitamin B12 and magnesium deficiency."},
            "Pantoprazole": {"MW": 383, "LogP": 2.1, "HBD": 1, "HBA": 7, "RotBonds": 6, "pass": True, "warning": "Fewer drug-drug interactions — preferred in polypharmacy."},
        },
        "ending": "Mrs. Roy's heartburn resolves in 2 weeks. Esophageal erosions heal on repeat endoscopy.",
    },
    # ── 20. OSTEOPOROSIS ─────────────────────────────────────────────────────
    {
        "id": 20, "title": "Bones That Break",
        "disease": "Osteoporosis", "difficulty": "⭐⭐⭐ Intermediate",
        "patient": {"name": "Mrs. Saxena", "age": 67, "gender": "Female",
            "condition": "Postmenopausal osteoporosis — low T-score and wrist fracture",
            "history": "DEXA scan: T-score -2.8. Needs anti-resorptive therapy."},
        "stage1_question": "Osteoclasts drive bone loss. Which enzyme do bisphosphonates inhibit to disable osteoclasts?",
        "stage1_options": [
            {"text": "Farnesyl pyrophosphate synthase (FPPS)", "correct": True,  "feedback": "Correct! Bisphosphonates block FPPS, disrupting osteoclast prenylation and function."},
            {"text": "Cathepsin K",                           "correct": False, "feedback": "Also an osteoclast target but for a different drug class (odanacatib)."},
            {"text": "Alkaline phosphatase",                  "correct": False, "feedback": "Made by osteoblasts (bone-forming cells), not osteoclasts."},
            {"text": "Carbonic anhydrase II",                 "correct": False, "feedback": "Helps osteoclasts but isn't the primary bisphosphonate target."},
        ],
        "target_protein": "FPPS", "target_pdb": "1ZW5",
        "pocket_regions": [
            {"name": "Allylic substrate binding site", "correct": True,  "feedback": "Correct! Bisphosphonates mimic the allylic substrate (geranyl PP) and bind here."},
            {"name": "Mg²⁺ binding loop",              "correct": False, "feedback": "Coordinates Mg cofactor but not the primary binding site."},
            {"name": "Dimer interface",                "correct": False, "feedback": "Structural element."},
            {"name": "C-terminal helix",               "correct": False, "feedback": "Not catalytic."},
        ],
        "candidates": [
            {"name": "Alendronate",     "desc": "First-line bisphosphonate",       "smiles": "NCCCC(O)(P(=O)(O)O)P(=O)(O)O",              "kind": "best"},
            {"name": "Risedronate",     "desc": "Pyridinyl bisphosphonate",        "smiles": "OC(Cc1cccnc1)(P(=O)(O)O)P(=O)(O)O",        "kind": "alt"},
            {"name": "Zoledronate",     "desc": "IV bisphosphonate — very potent", "smiles": "OC(Cn1ccnc1)(P(=O)(O)O)P(=O)(O)O",         "kind": "best"},
            {"name": "Calcium carbonate","desc": "Decoy — supplement only",        "smiles": "C(=O)([O-])[O-].[Ca+2]",                   "kind": "decoy"},
            {"name": "Vitamin D",       "desc": "Decoy — needed but not main drug","smiles": "CC(CCCC(C)C)C1CCC2C1(CCCC2=CC=C3CC(O)CCC3=C)C", "kind": "decoy"},
            {"name": "Glucose",         "desc": "Decoy — sugar",                   "smiles": "C(C1C(C(C(C(O1)O)O)O)O)O",                "kind": "decoy"},
        ],
        "off_target": "Geranylgeranyl PP synthase", "off_target_pdb": "2J1P",
        "selectivity_data": {
            "Alendronate": {"pass": True, "msg": "Good FPPS selectivity. Esophageal irritation risk with oral dosing."},
            "Zoledronate": {"pass": True, "msg": "Most potent bisphosphonate. IV only — given once yearly."},
        },
        "admet": {
            "Alendronate": {"MW": 249, "LogP": -3.0, "HBD": 5, "HBA": 7, "RotBonds": 5, "pass": False, "warning": "⚠️ Very poor oral absorption (<1%). Must take with water, stay upright. Rare jaw osteonecrosis."},
            "Zoledronate": {"MW": 272, "LogP": -3.5, "HBD": 4, "HBA": 7, "RotBonds": 3, "pass": False, "warning": "IV only — annual infusion is convenient."},
        },
        "ending": "Mrs. Saxena's bone density improves over 2 years. No further fractures with calcium and vitamin D continued.",
    },
]
